# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='photo',
            field=models.ImageField(blank=True, height_field=500, upload_to='uploads', width_field=500),
        ),
        migrations.AlterField(
            model_name='teste',
            name='name',
            field=models.TextField(),
        ),
    ]
