# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171016_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
